# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - csvtoml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://csvtoml.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ad971c2d0b844283b1598a8e32a36a2e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b7d904a6b272417885a7aee8d0bb11a3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: csvtoml.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ad971c2d0b844283b1598a8e32a36a2e }}/csvtoml:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'csvtoml'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_30e89c7978504770a7f1be5204cb12aa }}
        images: 'csvtoml.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ad971c2d0b844283b1598a8e32a36a2e }}/csvtoml:${{ github.sha }}'